const colors = {
  light: {
    text: "#0a0a0a",
    tint: "#3b9af5",
    background: "#f4f6f9",
    foreground: "#0a0a0a",
    card: "#ffffff",
    cardForeground: "#0a0a0a",
    primary: "#3b9af5",
    primaryForeground: "#ffffff",
    secondary: "#f0f4f8",
    secondaryForeground: "#1a1a1a",
    muted: "#f0f4f8",
    mutedForeground: "#6b7a90",
    accent: "#e8f0fe",
    accentForeground: "#1a1a1a",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#e2e8f0",
    input: "#e2e8f0",
    success: "#10b981",
    warning: "#f59e0b",
  },
  dark: {
    text: "#ecf1f9",
    tint: "#3b9af5",
    background: "#080e1f",
    foreground: "#ecf1f9",
    card: "#0c1529",
    cardForeground: "#ecf1f9",
    primary: "#3b9af5",
    primaryForeground: "#ffffff",
    secondary: "#141f30",
    secondaryForeground: "#ecf1f9",
    muted: "#141f30",
    mutedForeground: "#7a95b5",
    accent: "#1b2a3f",
    accentForeground: "#ecf1f9",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#1b2a3f",
    input: "#1b2a3f",
    success: "#10b981",
    warning: "#f59e0b",
  },
  radius: 10,
};

export default colors;
