uploads = []

[[generated]]
id = "4PXFOhZZOVvSx0owEG8zF"
uri = "file://artifacts/ck-mobile/assets/images/icon.png"
type = "image"
title = "ck-mobile-icon"

[[outputs]]
id = "YFZ4V5HwGRAMg1O5njydn"
uri = "file://ck-group-source.zip"
type = "unspecified"
title = "CK Group — Full Source Code (1 MB)"
